# datos.py

pildoras = [
    {"autor": "Marco Aurelio", "texto": "Tienes poder sobre tu mente, no sobre los acontecimientos externos. Date cuenta de esto."},
    {"autor": "Naval Ravikant", "texto": "Si no puedes ver el lado positivo, estás mirando con los ojos del ego."},
    {"autor": "David Goggins", "texto": "El sufrimiento es la única forma de crecer. Domina tu mente."},
    {"autor": "Séneca", "texto": "No es que tengamos poco tiempo, sino que perdemos mucho."}
]

MISIONES_DESARROLLO = [
  "Bloque de Deep Work: 0 móvil, 0 distracciones. Solo la tarea más difícil.",
    "Leer 10 páginas de filosofía estoica o ensayo.", 
    "Hacer 100 flexiones estrictas (divide en series si es necesario).",
    "Limpiar y organizar el espacio de trabajo como un quirófano.",
    "Sesión de meditación de 15 minutos en silencio absoluto.",
    "Escribir 500 palabras sobre tus objetivos a 5 años.",
    "Estirar todo el cuerpo durante 20 minutos sin interrupciones.",
    "Aprender un concepto nuevo de tu sector industrial.",
    "Barrer, fregar y ordenar una habitación de tu casa al 100%.",
    "Hacer 50 sentadillas y 50 abdominales explosivas.",
    "Planificar tu semana entera hora por hora en el calendario.",
    "Leer 15 páginas de un libro técnico o financiero.",
    "Vaciar la bandeja de entrada del correo a Cero (Inbox Zero).",
    "Escribir en papel 3 cosas por las que estás agradecido.",
    "Hacer una rutina de Yoga o Movilidad de 30 minutos.",
    "Avanzar en ese proyecto que llevas procrastinando 1 mes.",
    "Practicar un idioma extranjero de forma intensiva.",
    "Escuchar un podcast de desarrollo personal tomando notas.",
    "Diseñar tu menú de comidas saludables para los próximos 3 días.",
    "Hacer 200 saltos de comba o jumping jacks.",
    "Revisar tus finanzas: ingresos, gastos y ahorro del mes.",
    "Visualización activa: Imaginar tu fracaso si no trabajas hoy.",
    "Beber 1 litro de agua e hidratar el cerebro antes de seguir.",
    "Desinstalar o bloquear una app tóxica de tu móvil.",
    "Llamar a un familiar o mentor que te inspire respeto.",
    "Estudiar la biografía de un líder histórico.",
    "Hacer una caminata rápida o correr 3km sin música.",
    "Tomar una ducha de agua fría extrema.",
    "Identificar tu mayor debilidad actual y trazar un plan para matarla.",
    "Practicar respiración Wim Hof (3 rondas completas).",
    "No quejarte de nada ni de nadie durante todo el día de hoy.",
    "Redactar tu 'Antivisión': en quién te convertirás si eres vago.",
    "Trabajar de pie durante los próximos 45 minutos.",
    "Hacer una sesión de 100 burpees.",
    "Optimizar tu currículum o perfil profesional de LinkedIn.",
    "Aprender los atajos de teclado del programa que más usas.",
    "Eliminar archivos inútiles de tu ordenador (limpieza digital).",
    "Hacer 5 series al fallo de dominadas o flexiones.",
    "Investigar cómo diversificar tus fuentes de ingresos.",
    "Anotar 5 ideas de negocio o mejoras para tu trabajo.",
    "Practicar el silencio: no hablar a menos que sea 100% necesario.",
    "Aprender sobre inversión pasiva o fondos indexados.",
    "Limpiar la cocina a fondo, dejando el fregadero impecable.",
    "Repasar tus metas anuales y tachar lo irrelevante.",
    "Trabajar ininterrumpidamente hasta que duela el cerebro.",
    "Analizar tus rutinas de sueño y planear cómo dormir 8h reales.",
    "Hacer un ayuno intermitente o saltarte la comida basura hoy.",
    "Ver un documental técnico y hacer un resumen escrito.",
    "Ordenar tu armario y desechar la ropa que ya no usas.",
    "Leer sobre inteligencia emocional y aplicar un concepto hoy.",
    "Trazar el organigrama mental de tu vida y tus pilares.",
    "Hacer 15 minutos de planchas (planks) acumulados.",
    "Evitar el azúcar y los procesados al 100% durante 24 horas.",
    "Escribirle a alguien que admires pidiéndole un consejo.",
    "Reflexionar sobre la muerte (Memento Mori) y la urgencia de vivir.",
    "Leer un artículo sobre física cuántica o astronomía.",
    "No usar redes sociales hasta que caiga el sol.",
    "Crear una base de datos para organizar tus conocimientos (Notion/Obsidian).",
    "Realizar ejercicios de Kegel o core avanzado.",
    "Automatizar una tarea repetitiva que odies hacer.",
    "Preparar la ropa y los objetivos de mañana antes de dormir.",
    "Leer 20 páginas de la biografía de Elon Musk o Steve Jobs.",
    "Buscar 3 formas de ahorrar dinero esta semana.",
    "Hacer un entrenamiento de fuerza con tu peso corporal.",
    "Aprender a usar la terminal/consola de tu ordenador.",
    "Crear una copia de seguridad de todos tus datos importantes.",
    "Tener una conversación difícil que has estado evitando.",
    "Eliminar suscripciones o gastos hormiga de tus tarjetas.",
    "Consumir contenido exclusivo de matemáticas o lógica.",
    "Escribir tu propio manifiesto de guerra personal.",
    "Realizar una sesión de alta intensidad HIIT de 20 minutos.",
    "Aprender los fundamentos de la programación en Python/SQL.",
    "Organizar los cables y la limpieza física de tu set-up.",
    "Analizar tu lenguaje corporal en el espejo y mejorarlo.",
    "Dedicar tiempo a entender el mercado cripto/blockchain.",
    "Hacer 100 sentadillas búlgaras (50 por pierna).",
    "Planear un fin de semana de desconexión total en la naturaleza.",
    "Aprender a cocinar un plato altamente nutritivo y barato.",
    "Escribir un ensayo crítico sobre una opinión impopular que tengas.",
    "Desuscribirte de correos publicitarios (limpiar newsletter).",
    "Pasar 30 minutos al sol sin distracciones tecnológicas.",
    "Aprender técnicas de persuasión y ventas.",
    "Evaluar a tus 5 amigos más cercanos: ¿Te suman o te restan?",
    "Leer sobre economía austriaca o macroeconomía básica.",
    "Escribir un diario de errores: fallos recientes y cómo no repetirlos.",
    "Practicar mecanografía para aumentar tus pulsaciones por minuto.",
    "No consumir pornografía ni contenido basura. Dopamina limpia.",
    "Mejorar la seguridad de tus contraseñas usando un gestor.",
    "Aprender sobre inteligencia artificial y automatización de IA.",
    "Hacer 10 series de sprints cuesta arriba.",
    "Ver un TED Talk sobre psicología humana o neurociencia.",
    "Diseñar una rutina matutina inquebrantable de 60 minutos.",
    "Auditar tu postura en la silla y corregirla conscientemente.",
    "Identificar qué tarea te da el 80% de tus resultados (Ley de Pareto).",
    "Hacer una lista de los peores escenarios posibles y prepararte para ellos.",
    "Aprender primeros auxilios básicos o maniobra de Heimlich.",
    "Construir tu propia página web o portafolio personal.",
    "Renunciar a la cafeína durante todo el día para resetear receptores.",
    "Memorizar frases clave en latín estoico (Amor Fati, Veni Vidi Vici).",
    "Investigar la historia militar de Roma o Esparta para forjar carácter."
]
