# idiomas.py

DIC = {
    "es": {
        "lang_btn": "🇺🇸 EN",
        "nav_lobby": "🏠 LOBBY",
        "nav_gremio": "⚔️ GREMIO",
        "nav_mundo": "🌍 MUNDO",
        "nav_tienda": "🛒 TIENDA",
        "nav_cuartel": "🛡️ CUARTEL",
        "log_title": "LA ARENA",
        "log_manifesto": "El mundo está lleno de gente que abandona cuando duele.<br><span class='highlight'>Nosotros venimos a romper al 99%.</span>",
        "log_carcel_tit": "⚔️ La Cárcel para tu Móvil",
        "log_carcel_desc": "Abre la app en tu teléfono y déjalo en la mesa. Si sales de la pantalla para mirar redes sociales, tu escudo colapsa y pierdes ELO.",
        "log_mercado_tit": "🪙 Mercado Negro de Skins",
        "log_mercado_desc": "Sobrevive a tus sesiones de estudio para ganar monedas. Abre cofres y equipa auras y neones.",
        "log_ranking_tit": "🏆 Ranking Mundial y Temporadas",
        "log_ranking_desc": "Sube desde Hierro III hasta Diamante. Solo los más disciplinados alcanzan el Salón de los Dioses.",
        "tab_login": "🚪 ENTRAR AL COLISEO",
        "tab_reg": "📝 FORJAR UNA LEYENDA",
        "ph_email": "Correo electrónico",
        "ph_pass": "Contraseña",
        "ph_name": "Nombre de guerra (Tu Código)",
        "ph_ref": "¿Quién te ha reclutado? (Opcional)",
        "btn_acceder": "ACCEDER",
        "btn_jurar": "JURAR LEALTAD",
        "lobby_title": "⚔️ MODO COMBATE",
        "lobby_welcome": "Bienvenido, {nombre}",
        "lobby_rank": "Tu Rango",
        "lobby_elo": "ELO",
        "lobby_vault": "Bóveda",
        "lobby_contracts": "📜 CONTRATOS MERCENARIOS",
        "lobby_prog_daily": "Progreso Diario",
        "lobby_m1_title": "Primer Sangrado",
        "lobby_m1_desc": "Gana 1 combate",
        "lobby_m2_title": "Asesino a Sueldo",
        "lobby_m2_desc": "Gana 2 escaramuzas",
        "lobby_m3_title": "El Titán",
        "lobby_m3_desc": "Sobrevive 1 asalto",
        "lobby_btn_claim": "🎁 RECLAMAR",
        "lobby_btn_claimed": "✅ RECLAMADO",
        "lobby_btn_missing1": "Falta 1",
        "lobby_btn_missing_multi": "Faltan {n}",
        "lobby_rules_title": "⚠️ Las Leyes de la Arena",
        "lobby_rules_1": "📱 <span class='neon-green'>CÓMO SE JUEGA:</span> Abre esto en tu móvil, déjalo en la mesa y ve a trabajar en tu PC o en tus libros.",
        "lobby_rules_2": "🔴 <span class='neon-red'>CÓMO PIERDES:</span> Si coges el móvil y cambias de app, tu escudo colapsa y pierdes ELO.",
        "lobby_rules_3": "⚔️ <strong style='color: #ffd700;'>EL PACTO:</strong> Convierte tu móvil en tu propio vigilante. No te engañes a ti mismo.",
        "lobby_dec_title": "🔥 DECLARACIÓN DE INTENCIONES",
        "lobby_ph_mision": "Ej: Terminar el ensayo de Filosofía...",
        "lobby_duration": "Duración de la batalla:",
        "lobby_btn_global": "🌍 BÚSQUEDA MUNDIAL",
        "lobby_err_mision": "Un guerrero no entra sin propósito. Declara tu misión o usa el dado 🎲.",
        "lobby_priv_title": "🤝 DUELO PRIVADO",
        "lobby_ph_code": "Pega código o vacío para crear",
        "lobby_btn_priv": "🚪 CREAR / UNIRSE"
    },
    "en": {
        "lang_btn": "🇪🇸 ES",
        "nav_lobby": "🏠 LOBBY",
        "nav_gremio": "⚔️ GUILD",
        "nav_mundo": "🌍 WORLD",
        "nav_tienda": "🛒 STORE",
        "nav_cuartel": "🛡️ BARRACKS",
        "log_title": "THE ARENA",
        "log_manifesto": "The world is full of people who quit when it hurts.<br><span class='highlight'>We are here to break the 99%.</span>",
        "log_carcel_tit": "⚔️ The Mobile Prison",
        "log_carcel_desc": "Open the app on your phone and leave it on the desk. If you leave the screen to check social media, your shield collapses and you lose ELO.",
        "log_mercado_tit": "🪙 Black Market Skins",
        "log_mercado_desc": "Survive your focus sessions to earn coins. Open chests and equip auras and neons.",
        "log_ranking_tit": "🏆 Global Ranking & Seasons",
        "log_ranking_desc": "Climb from Iron III to Diamond. Only the most disciplined reach the Hall of Gods.",
        "tab_login": "🚪 ENTER THE COLOSSEUM",
        "tab_reg": "📝 FORGE A LEGEND",
        "ph_email": "Email address",
        "ph_pass": "Password",
        "ph_name": "War Name (Your Tag)",
        "ph_ref": "Who recruited you? (Optional)",
        "btn_acceder": "ENTER",
        "btn_jurar": "SWEAR LOYALTY",
        "lobby_title": "⚔️ COMBAT MODE",
        "lobby_welcome": "Welcome, {nombre}",
        "lobby_rank": "Your Rank",
        "lobby_elo": "ELO",
        "lobby_vault": "Vault",
        "lobby_contracts": "📜 MERCENARY CONTRACTS",
        "lobby_prog_daily": "Daily Progress",
        "lobby_m1_title": "First Blood",
        "lobby_m1_desc": "Win 1 combat",
        "lobby_m2_title": "Hitman",
        "lobby_m2_desc": "Win 2 skirmishes",
        "lobby_m3_title": "The Titan",
        "lobby_m3_desc": "Survive 1 assault",
        "lobby_btn_claim": "🎁 CLAIM",
        "lobby_btn_claimed": "✅ CLAIMED",
        "lobby_btn_missing1": "Missing 1",
        "lobby_btn_missing_multi": "Missing {n}",
        "lobby_rules_title": "⚠️ The Laws of the Arena",
        "lobby_rules_1": "📱 <span class='neon-green'>HOW TO PLAY:</span> Open this on your phone, leave it on the desk and go work on your PC or books.",
        "lobby_rules_2": "🔴 <span class='neon-red'>HOW TO LOSE:</span> If you pick up your phone and change apps, your shield collapses and you lose ELO.",
        "lobby_rules_3": "⚔️ <strong style='color: #ffd700;'>THE PACT:</strong> Turn your phone into your own warden. Don't fool yourself.",
        "lobby_dec_title": "🔥 DECLARATION OF INTENT",
        "lobby_ph_mision": "Ex: Finish the Philosophy essay...",
        "lobby_duration": "Battle duration:",
        "lobby_btn_global": "🌍 GLOBAL SEARCH",
        "lobby_err_mision": "A warrior does not enter without purpose. Declare your mission or use the dice 🎲.",
        "lobby_priv_title": "🤝 PRIVATE DUEL",
        "lobby_ph_code": "Paste code or leave empty to create",
        "lobby_btn_priv": "🚪 CREATE / JOIN"
    }
}
